name: deploy-to-azure

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Container App image
        run: |
          az containerapp update \
            --name reisetagebuch \
            --resource-group summherum-devops \
            --image ghcr.io/${{ github.repository }}/reisetagebuch:latest
