name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Maven Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Artefakt 
        uses: actions/upload-artifact@v4
        with:
            name: Reisetagebuch
            path: target/*.jar


      - name: Build und Tests
        run: mvn clean verify
